### PR TITLE
Made register and login views responsive

### PR DESCRIPTION
**Pull request by codewitgabi**
Screenshot_20230804-065833
Screenshot_20230804-065843

This is a fix for #9 for register and login views. They upper part of the forms seem not to be showing. Now, they show.

### CODE REVIEW

**Review by VinCoD — APPROVED** [review]
Next time. Please try to only push the files you have changed to github. Dont push the users/__pycache__/

Also, create branches for your changes

**Comment by codewitgabi** [comment]
I added it to .gitignore but i guess it didn't ignore it. I'll do just that next time.

**Comment by codewitgabi** [comment]
I'm currently using `auth-update` do I need to create new ones for different changes?

**Comment by codewitgabi** [comment]
I'm currently using `auth-update` do I need to create new ones for different changes?

**Comment by VinCoD** [comment]
.gitignore cannot work if a file is already being tracked by git. It should always be done before you commit a file.  There is a process of stopping git from tracking a file but it is not simple and can lead to errors, so instead just commit specific files like git add linkshare/settings.py or links/templates/links.html.

**Pull request merged**
