### PR TITLE
Updated authentication

### PR DESCRIPTION
**Pull request by codewitgabi**
- Changed user model
- Updated user registration and login
- Added reset password functionality.
-  Styling needs to be added though as only the functionalities we're done.

### CODE REVIEW

**Comment by VinCoD** [comment]
Please Add a Screenshot of how the new authentication you have added looks like.

**Comment by codewitgabi** [comment]
Ok I'll do that

**Comment by codewitgabi** [comment]
Screenshot_20230731-021704~2
This page is for the request password view and it's responsive with my recent push.

Screenshot_20230731-022307~2

Here, the user is alerted to check their email for further walk through on how to rest their password.

**Comment by codewitgabi** [comment]
Other views have not been styled yet but all functionalities have been implemented and tested.

**Pull request merged**
